version: "3"

services:
  postgresql:
    image: postgres:12.3-alpine
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: calendar
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    networks:
      - network
    hostname: localhost

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - network
    hostname: localhost

  web-app:
    image: alpine:latest
    container_name: web-app
    command: ./bin/calendar
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      REDIS_URL: redis://h:@redis:6379
      DATABASE_URL: postgresql://testuser:password@postgresql:5432/calendar?sslmode=disable
    depends_on:
      - postgresql
      - redis
    networks:
      - network
    hostname: localhost
    tty: true 

networks:
  network:
    driver: bridge