version: "3"

services:
  postgresql:
    image: postgres:12.3-alpine
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: calendar
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: localhost

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    hostname: localhost
